### ISSUE TITLE
Encounter Error When No Git Repo Found

### ISSUE THREAD

**Issue by maquedexiju** [Gruntfuggly/rename-actions#4]
Hi, I'm using OSX and I can't get it work at first because there is no git repo in my path.
I checked the extensions.js and found

```
var repo = ( exec( 'git rev-parse --show-toplevel', { cwd: folder } ) + "" ).trim();
```

Actually, this command will return

```
Error: Command failed: git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
```

So I think you may need to add a "try and catch" here in case there is no git repo here.
Looking forwards to an update ; - )

**Comment by maquedexiju** [comment]
By the way, this is really a awesome extension, good job and thanks a lot

**Comment by Gruntfuggly** [comment]
Should now be working in the latest version.
